name = "tanstack-start-ts"
main = "./.output/server/index.mjs"
compatibility_date = "2026-07-21"
compatibility_flags = [ "nodejs_compat" ]
no_bundle = true

[assets]
directory = "./.output/public"
binding = "ASSETS"

[[rules]]
type = "ESModule"
globs = [ "**/*.mjs", "**/*.js" ]
