// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createMockSupabaseClient() {
  const mockUser = { id: "mock-user-123", email: "demo@example.com" };
  const mockSession = { user: mockUser };

  function createDeepProxy(target = {}, tableName?: string): any {
    return new Proxy(target, {
      get(obj, prop) {
        if (prop === 'then') {
          return (resolve: any) => {
            if (tableName === 'products') {
              resolve({ data: [
                {
                  id: "1",
                  name: "Chronograph Masterpiece",
                  description: "Swiss-made precision watch.",
                  category: "Horology",
                  price_cents: 1250000,
                  currency: "usd",
                  stock: 3,
                  featured: true,
                  image_url: "/assets/product-1.jpg"
                },
                {
                  id: "2",
                  name: "Vintage Leather Briefcase",
                  description: "Hand-stitched Italian calf leather.",
                  category: "Leather Goods",
                  price_cents: 350000,
                  currency: "usd",
                  stock: 10,
                  featured: true,
                  image_url: "/assets/product-2.jpg"
                },
                {
                  id: "3",
                  name: "Aero X-1 Jet Consultation",
                  description: "Private jet purchase consulting.",
                  category: "Aviation",
                  price_cents: 5000000,
                  currency: "usd",
                  stock: 1,
                  featured: true,
                  image_url: "/assets/product-3.jpg"
                }
              ], error: null });
            } else {
              resolve({ data: [], error: null });
            }
          };
        }
        if (prop === 'maybeSingle') {
          return async () => ({ data: null, error: null });
        }
        if (prop === 'auth') {
          return {
            getUser: async () => ({ data: { user: mockUser }, error: null }),
            getSession: async () => ({ data: { session: mockSession }, error: null }),
            onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
            signUp: async () => ({ data: { user: mockUser, session: mockSession }, error: null }),
            signInWithPassword: async () => ({ data: { user: mockUser, session: mockSession }, error: null }),
            signOut: async () => ({ error: null }),
            updateUser: async () => ({ data: { user: mockUser }, error: null }),
            exchangeCodeForSession: async () => ({ data: { session: mockSession }, error: null })
          };
        }
        if (prop === 'from') {
          return (table: string) => createDeepProxy({}, table);
        }
        if (typeof prop === 'string' && ['channel', 'on', 'subscribe', 'select', 'insert', 'update', 'delete', 'upsert', 'eq', 'order', 'limit'].includes(prop)) {
          return () => createDeepProxy({}, tableName);
        }
        if (prop === 'removeChannel') {
          return () => {};
        }
        return Reflect.get(obj, prop);
      }
    });
  }

  return createDeepProxy();
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn("[Supabase] Missing keys. Running in MOCK mode.");
    return createMockSupabaseClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: "pkce",
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
